### ISSUE TITLE
No GTM script is rendered on build

### ISSUE THREAD

**Issue by callumflack** [sergeyfilimonov/gridsome-plugin-gtm#1]
See: https://avaricapitalpartners.com.au/

![image](https://user-images.githubusercontent.com/749885/55303162-ea50e900-5487-11e9-9ab9-b12013702913.png)

Do I need to add something into `main.js`?

**Comment by Sparo** [comment]
Hi @callumflack,

can you tell me what was the solution to this problem, not rendering gtag on build?

I seem not to understand what needs to be done...

tnx in advance...
